resume: False
weight: checkpoints/sunrefer_pretrain/model_latest.pth
hm_model_resume: checkpoints/sunrefer_voxel_match_pretrain/model_best.pth
method: refer
exp_name: sunrefer
isTrain: True
device:
  use_gpu: True
  gpu_ids: '1'
data:
  dataset: sunrefer
  sigma: 0.5
  debug: True
  use_color : True
  use_aug: True
  num_points: 20000
  use_refine: True
  voxel_size: 0.05
  num_sample: 1000 #if -1, use all sample, if >0, use limited number of sample
  val_path: ./data/sunrefer_singleRGBD/SUNREFER_val.pkl
  train_path: ./data/sunrefer_singleRGBD/SUNREFER_train.pkl
  data_path: ./data/sunrefer_singleRGBD/sunrgbd_pc_bbox_votes_30k_v2
  MAX_DES_LEN: 117
  MAX_NUM_OBJ: 128
  batch_size: 4
  num_workers: 8
model:
  t: 2
  alpha: 0.5
  max_nseed: 256
  pcd_in_channels: 3
  pcd_hidden_size: 256
  lang_hidden_size: 256
optimizer:
  method: Adam
  lr_ref: 1e-3
  lr_hm: 1e-4
  beta1: 0.9
  beta2: 0.999
scheduler:
  gamma: 0.2
visualization:
  model_vis_interval: 10000
other:
  clean_cache_interval: 100
  nepoch: 100
  model_save_interval: 1
  model_save_dir: ./checkpoints
loss:
  w_matching: 2
  w_response: 1
  w_contain: 1
  w_heatmap: 0.5
  w_ref: 0.1
  w_vote: 0.5
  use_vote_l1: True


